### ISSUE TITLE
Fix 595 not showing and "magical" *_all partials

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1120]
In the marc view show partials which end with `_all` will apply to all the tags in the group. Ex.

```
  show_distribution:
    all_tags: 
    - "594"
    all_tag_templates: 
      "594": marc_show/show_distribution_all
```

`show_distribution_all` gets a `tags` variable with 594 *and* 595. The unforeseen side effect here is that `show_distribution_all` deals only with the display of 594 so 595s are not displayed.  This is quite a hack to concatenate together tags of the same type, in this case all the 594s need to be concatenated for display:

```V (6), vl (2), vla, bc, ob (2), cor (2)```

It happens in https://github.com/rism-digital/muscat/blob/2025fb6f7b24a8b52ff9f62194c00fbbb745b7c8/app/views/marc/_show_tags.html.erb#L5 with a hadcoded piece of code. This should be cleaned up and a proper solution found.

There are two steps:

- [ ] Move 595 to another group so it is visualized
- [ ] Remove the obscure functionality with _all and add a proper implementation

Related to #595
