### ISSUE TITLE
"mandatory" does not work in server side validation

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1412]
the "mandatory" rule does nothing if the whole tag is there but only the subtag is missing. Ex:

```yml
  "852":
    tags:
      c: mandatory
      x: mandatory
```
Will complain if 852 is missing completely but raise no error if 852 $x is there but not $c.
