### ISSUE TITLE
Remove option "digitized" in 856$x for prints

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1415]
As with https://github.com/rism-digital/muscat/issues/1414, the option `Digitized` in 856$x in the main bib record in print templates results in people adding information that really belongs in the holdings. 

Please remove it from the drop-down menu in the following templates (main bib record in Sources):

- edition
- libretto_edition
- theoretica_edition
- edition_content
- libretto_edition_content
- theoretica_edition_content

**Comment by jenniferward** [comment]
Now it occurs to me: What about the IIIF options @lpugin @baccia @BaMikusi ? Maybe we should just limit it to `Other` here?

**Comment by BaMikusi** [comment]
At the moment IIIF entries seem mostly to be available only for digitized sources, though I have recently learned that the BSB now also offers these for water marks, so it's probably a bit of a moving target. At any rate, I should think that the options should essentially be symmetrical in both cases, so -- out of the four options we have now -- only the two "others" should remain, i.e. "Other" and "IIIF manifest (other)".

**Comment by xhero** [comment]
I implemented the items as per above, it looks like this at the moment:

```yml
    codes:
      - "IIIF manifest (digitized source)"
      - "IIIF manifest (other)"
      - "Digitized"
      - "Other"
    codes_edition:
      - "IIIF manifest (other)"
      - "Other"
    codes_libretto_edition:
      - "IIIF manifest (other)"
      - "Other"
    codes_theoretica_edition:
      - "IIIF manifest (other)"
      - "Other"
    codes_edition_content:
      - "IIIF manifest (other)"
      - "Other"
    codes_libretto_edition_content:
      - "IIIF manifest (other)"
      - "Other"
    codes_theoretica_edition_content:
      - "IIIF manifest (other)"
      - "Other"
```

@jenniferward @BaMikusi does the list look ok?
